import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ProjectManagementGateway } from '../application/project-management.gateway';
import { Proyecto } from '../domain/model/proyecto.model';
import { PuntoMonitoreo } from '../domain/model/punto-monitoreo.model';
import { Responsable } from '../domain/model/responsable.model';

const MOCK_PROYECTOS: Proyecto[] = [
  {
    id: 'PRY-001',
    nombre: 'Panamericana Sur – Chilca',
    ubicacion: 'Chilca, Lima',
    region: 'Lima',
    constructora: 'Obras del Sur SA',
    supervisor: 'Ing. María Torres',
    saludAmbiental: 64,
    alertasActivas: 9,
    incidentes: 12,
    incidenciasCriticas: 3,
    estado: 'en_progreso',
    fechaInicio: '2026-02-01',
    fechaFin: '2027-02-28',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:41:00',
  },
  {
    id: 'PRY-002',
    nombre: 'Longitudinal de la Sierra – Tramo 3',
    ubicacion: 'Cajamarca',
    region: 'Cajamarca',
    constructora: 'Vías del Norte SAC',
    supervisor: 'Ing. Carlos Rivas',
    saludAmbiental: 78,
    alertasActivas: 4,
    incidentes: 6,
    incidenciasCriticas: 1,
    estado: 'en_progreso',
    fechaInicio: '2026-01-15',
    fechaFin: '2027-06-15',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:35:00',
  },
  {
    id: 'PRY-003',
    nombre: 'Carretera Central – Tramo 2',
    ubicacion: 'Junín',
    region: 'Junín',
    constructora: 'Consorcio Vial Andino',
    supervisor: 'Ing. Sofía Mendoza',
    saludAmbiental: 87,
    alertasActivas: 5,
    incidentes: 7,
    incidenciasCriticas: 2,
    estado: 'en_progreso',
    fechaInicio: '2026-03-01',
    fechaFin: '2027-03-31',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:42:00',
  },
  {
    id: 'PRY-004',
    nombre: 'Interoceánica – Tramo 4',
    ubicacion: 'Madre de Dios',
    region: 'Madre de Dios',
    constructora: 'Consorcio Amazónico',
    supervisor: 'Ing. Roberto Díaz',
    saludAmbiental: 91,
    alertasActivas: 2,
    incidentes: 2,
    incidenciasCriticas: 0,
    estado: 'en_progreso',
    fechaInicio: '2026-04-10',
    fechaFin: '2027-04-10',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:38:00',
  },
  {
    id: 'PRY-005',
    nombre: 'Vía de Evitamiento Norte',
    ubicacion: 'Los Olivos, Lima',
    region: 'Lima',
    constructora: 'Constructora Pacífico SAC',
    supervisor: 'Ing. Ana Flores',
    saludAmbiental: 96,
    alertasActivas: 1,
    incidentes: 1,
    incidenciasCriticas: 0,
    estado: 'en_progreso',
    fechaInicio: '2026-05-01',
    fechaFin: '2026-12-15',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:40:00',
  },
  {
    id: 'PRY-006',
    nombre: 'Red Vial 6 – Pucusana',
    ubicacion: 'Pucusana, Lima',
    region: 'Lima',
    constructora: 'Constructora Pacífico SAC',
    supervisor: 'Ing. Luis Paredes',
    saludAmbiental: 99,
    alertasActivas: 0,
    incidentes: 0,
    incidenciasCriticas: 0,
    estado: 'en_progreso',
    fechaInicio: '2026-06-01',
    fechaFin: '2027-01-31',
    sensoresActivos: 8,
    totalSensores: 8,
    ultimaLectura: '2026-09-30T10:42:00',
  },
];

const ECA_AIRE = 'ECA Aire • D.S. 003-2017-MINAM';
const ECA_RUIDO = 'ECA Ruido • D.S. 085-2003-PCM';
const ECA_AGUA = 'ECA Agua • D.S. 004-2017-MINAM';

// Puntos del proyecto PRY-003 (Carretera Central – Tramo 2), según el mockup
const MOCK_PUNTOS: PuntoMonitoreo[] = [
  {
    id: 'N-01',
    proyectoId: 'PRY-003',
    progresiva: 'Km 46+100',
    indicador: 'aire',
    parametro: 'PM10',
    lmp: '100 µg/m³',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '41 µg/m³',
    estado: 'optimo',
    latitud: -11.7612,
    longitud: -75.5102,
    norma: ECA_AIRE,
    advertenciaPct: 90,
  },
  {
    id: 'N-02',
    proyectoId: 'PRY-003',
    progresiva: 'Km 48+900',
    indicador: 'ruido',
    parametro: 'Ruido',
    lmp: '80 dB(A)',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '68 dB(A)',
    estado: 'optimo',
    latitud: -11.7655,
    longitud: -75.5051,
    norma: ECA_RUIDO,
    advertenciaPct: 90,
  },
  {
    id: 'N-03',
    proyectoId: 'PRY-003',
    progresiva: 'Km 51+400',
    indicador: 'aire',
    parametro: 'PM10',
    lmp: '100 µg/m³',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '93 µg/m³',
    estado: 'advertencia',
    latitud: -11.7702,
    longitud: -75.4981,
    norma: ECA_AIRE,
    advertenciaPct: 90,
  },
  {
    id: 'N-04',
    proyectoId: 'PRY-003',
    progresiva: 'Km 55+200',
    indicador: 'ruido',
    parametro: 'Ruido',
    lmp: '80 dB(A)',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '86 dB(A)',
    estado: 'critico',
    latitud: -11.7741,
    longitud: -75.4903,
    norma: ECA_RUIDO,
    advertenciaPct: 90,
  },
  {
    id: 'N-05',
    proyectoId: 'PRY-003',
    progresiva: 'Km 58+300',
    indicador: 'agua',
    parametro: 'pH',
    lmp: '6.5 – 8.5',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: 'pH 7.4',
    estado: 'optimo',
    latitud: -11.7788,
    longitud: -75.4847,
    norma: ECA_AGUA,
    advertenciaPct: 90,
  },
  {
    id: 'N-06',
    proyectoId: 'PRY-003',
    progresiva: 'Km 62+800',
    indicador: 'aire',
    parametro: 'PM10',
    lmp: '100 µg/m³',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '91 µg/m³',
    estado: 'advertencia',
    latitud: -11.7829,
    longitud: -75.4769,
    norma: ECA_AIRE,
    advertenciaPct: 90,
  },
  {
    id: 'N-07',
    proyectoId: 'PRY-003',
    progresiva: 'Km 65+000',
    indicador: 'ruido',
    parametro: 'Ruido',
    lmp: '80 dB(A)',
    nodoEnLinea: true,
    calibrado: '07/2026',
    ultimaLectura: '71 dB(A)',
    estado: 'optimo',
    latitud: -11.7873,
    longitud: -75.4701,
    norma: ECA_RUIDO,
    advertenciaPct: 90,
  },
  {
    id: 'N-08',
    proyectoId: 'PRY-003',
    progresiva: 'Km 60+100',
    indicador: 'agua',
    parametro: 'Turbidez',
    lmp: '100 NTU',
    nodoEnLinea: false,
    calibrado: '07/2026',
    ultimaLectura: null,
    estado: 'sin_conexion',
    latitud: -11.7805,
    longitud: -75.4811,
    norma: ECA_AGUA,
    advertenciaPct: 90,
  },
];

const MOCK_RESPONSABLES: Responsable[] = [
  {
    id: 'RES-001',
    proyectoId: 'PRY-001',
    nombre: 'Ing. María Torres',
    cargo: 'Supervisora ambiental',
    correo: 'mtorres@roadwatch.pe',
  },
  {
    id: 'RES-002',
    proyectoId: 'PRY-002',
    nombre: 'Ing. Carlos Rivas',
    cargo: 'Supervisor ambiental',
    correo: 'crivas@roadwatch.pe',
  },
  {
    id: 'RES-003',
    proyectoId: 'PRY-003',
    nombre: 'Carlos Mendoza',
    cargo: 'Jefe de Proyectos Viales',
    correo: 'cmendoza@roadwatch.pe',
  },
  {
    id: 'RES-004',
    proyectoId: 'PRY-003',
    nombre: 'Ing. Sofía Mendoza',
    cargo: 'Supervisora ambiental',
    correo: 'smendoza@roadwatch.pe',
  },
  {
    id: 'RES-005',
    proyectoId: 'PRY-004',
    nombre: 'Ing. Roberto Díaz',
    cargo: 'Supervisor ambiental',
    correo: 'rdiaz@roadwatch.pe',
  },
  {
    id: 'RES-006',
    proyectoId: 'PRY-005',
    nombre: 'Ing. Ana Flores',
    cargo: 'Supervisora ambiental',
    correo: 'aflores@roadwatch.pe',
  },
];

@Injectable({ providedIn: 'root' })
export class ProjectManagementMockAdapter extends ProjectManagementGateway {
  override getProyectos(): Observable<Proyecto[]> {
    return of(MOCK_PROYECTOS);
  }

  override getProyectoById(id: string): Observable<Proyecto | undefined> {
    return of(MOCK_PROYECTOS.find((p) => p.id === id));
  }

  override getPuntosMonitoreo(proyectoId: string): Observable<PuntoMonitoreo[]> {
    return of(MOCK_PUNTOS.filter((p) => p.proyectoId === proyectoId));
  }

  override getResponsables(proyectoId: string): Observable<Responsable[]> {
    return of(MOCK_RESPONSABLES.filter((r) => r.proyectoId === proyectoId));
  }
}
